service: senac-pc

custom:
  vpcID: "vpc-0df351153bc7efddd"
  vpcSubnetID: "subnet-094a3db510feb76f3"

  keyName: sandisk-key

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  stage: prd
  environment:
    INSTANCE_ID: "Teste"
    VOLUME_ID: !Ref Volume

resources:
  Resources:
    SecurityGroupSSH:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: ${self:custom.vpcID}
        GroupDescription: ${self:service}-ssh-sg
        GroupName: ${self:service}-ssh-sg

    SSHOutboundRule:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
          CidrIp: 186.239.253.173/0

          IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          GroupId:
            Fn::GetAtt:
              - SecurityGroupSSH
              - GroupId

    SSHInboundRule:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
          CidrIp: 186.239.253.173/0

          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          GroupId:
            Fn::GetAtt:
              - SecurityGroupSSH
              - GroupId

    Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-05240a8eacac22db2
        KeyName: ${self:custom.keyName}
        InstanceType: t2.micro

        SubnetId: ${self:custom.vpcSubnetID}
        SecurityGroupIds:
          - !Ref SecurityGroupSSH

        # Volumes:
        #   - Device: /dev/sdf
        #     VolumeId: !Ref Volume

        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install git
            git clone https://github.com/kcalixto/senac-pc-infra
            chmod 700 ./senac-pc-infra/init.sh
            ./senac-pc-infra/init.sh

    # Volume:
    #   Type: AWS::EC2::Volume
    #   Properties: 
    #     AvailabilityZone: sa-east-1a
    #     Size: 8
    #     VolumeType: gp3