name: "senac-pc"

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Install Dependencies
        run: |
          npm install --save-dev
          npm install serverless -g

      - name: Detach instance volume
        run: npm run detach

      - name: Deploy Serverless
        run: sls deploy --verbose
